# Generated by Django 2.0.7 on 2018-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile_app', '0002_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='boarding_services',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='vet',
            name='emergency_services',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='vet',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
