# Generated by Django 2.0.7 on 2018-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile_app', '0004_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='raw_address2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
