# Generated by Django 2.0.7 on 2018-07-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile_app', '0006_illness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=255, null=True)),
                ('contact_phone', models.CharField(max_length=25, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
