# Generated by Django 2.0.7 on 2018-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile_app', '0010_auto_20180717_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
