# Generated by Django 2.0.7 on 2018-07-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile_app', '0011_auto_20180717_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='raw_address2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
