# Generated by Django 2.0.7 on 2018-07-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile_app', '0012_auto_20180717_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='vet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
