# Generated by Django 2.0.7 on 2018-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile_app', '0013_auto_20180718_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='illness',
            name='species_affected',
            field=models.TextField(default='bearded dragons'),
            preserve_default=False,
        ),
    ]
