# Generated by Django 2.0.7 on 2018-08-01 13:27

from django.db import migrations

def add_illnesses(apps, schema_editor):
    Illness = apps.get_model("reptile_app", "Illness")
    data = [
    {
    "illness_name": "Metabolic bone disease (MBD)",
    "symptoms": "swelling of the lower jaw, softening of the jaw and facial bones, and swelling of the hind legs",
    "description": """MBD is one of the most common diseases in bearded dragons and is typically caused by a lack of
    nutrition (high phosphorous or low calcium).  Can also be caused by a lack of UV-B light.""",
    "species_affected": "bearded dragons, iguanas, chameleons"
    },
    {
    "illness_name": "Infectious Stomatitis (Mouth Rot) ",
    "symptoms": "hemorrhages on the gums, swollen gums, or an excess amount of thick mucus in the mouth",
    "description": "Bacterial infection of the mouth.  More common in iguanas than bearded dragons.",
    "species_affected": "bearded dragons, iguanas"
    },
    {
    "illness_name": "Parasites",
    "symptoms": "diarrhea, weight loss, unusual fecal matter",
    "description": """Often the pet will show no signs of an issue but this is usually caught during annual fecal examaminations.
    Can often be caused by feeding of wild insects.""",
    "species_affected": "bearded dragons, iguanas, chameleons"
    },
    {
    "illness_name": "Respiratory infections or pneumonia",
    "symptoms": "sneezing, discharge from the nose or eyes, bubbles in the mouth, unnatural breathing, gasping for breath, and lethargy",
    "description": "",
    "species_affected": "bearded dragons, iguanas, chameleons"
    },
    {
    "illness_name": "Hypervitaminosis D",
    "symptoms": "lack of appetite and lethargy",
    "description": "Typically caused by giving the pet too many supplements, or if feeding dog/cat food.",
    "species_affected": "bearded dragons, iguanas"
    },
    {
    "illness_name": "Edema",
    "symptoms": "swelling in the neck, throat, and chest.",
    "description": "Swelling in the body caused by excess fluids.  Can often be caused by overly high humidity, or by over-feeding vitamins.",
    "species_affected": "chameleons"
    },
    {
    "illness_name": "Calcium Defenciency",
    "symptoms": "soft bones, soft jaw, lethargy, lack of appetite, deformities in the spine or legs",
    "description": "Caused by a lack of calcium in the diet.  Can be easily prevented by dusting feeders with a calcium supplement.",
    "species_affected": "chameleons, bearded dragons, iguanas"
    },
    {
    "illness_name": "Vitamin A Deficiency",
    "symptoms": "reduced growth rate, swollen limbs, skin abnormalities, loss of appetite, swelling in the eyes, liver enlargement",
    "description": "Caused by a lack of vitamin A in the diet.  Can be easily prevented by dusting feeders with a multi-vitamin supplement that contains vitamin A 2.",
    "species_affected": "chameleons, bearded dragons, iguanas"
    },
    {
    "illness_name": "Dehydration",
    "symptoms": "orange or yellow urate, sunken eyes, loss of appetite and weak skin",
    "description": "Amount of hydration needed depends on the species, see specifics for your pet.",
    "species_affected": "chameleons, bearded dragons, iguanas"
    },
    {
    "illness_name": "Gout",
    "symptoms": "excessive drinking, not eating, reduced mobility, and swelling in the joints",
    "description": "Caused by an excess of uric acid in the blood.  Avoid feeding your pet foods that are high in protein.",
    "species_affected": "chameleons"
    },
    {
    "illness_name": "Egg Binding",
    "symptoms": "Lethargic, depressed, and inactive. Raising of the hind limbs and straining without producing any eggs.",
    "description": """Can be caused by anatomical defects, large malformed eggs, poor condition of the mother,
    lack of a good nesting site, dehydration or improper temperature""",
    "species_affected": "chameleons, bearded dragons"
    },
    {
    "illness_name": "Impaction",
    "symptoms": "loss of appetite, lethargic, and may have tightness or swelling in the lower stomach",
    "description": """Casued by a blockage in the digestive system.  Avoid feeding insects that are high in chiton.
    Loose substrates often contribute to this as well so it's recommended to stick to reptile carpet or tile as opposed to sand.""",
    "species_affected": "bearded dragon"
    },
    {
    "illness_name": "Atadenovirus (aka wasting sickness, stargazing)",
    "symptoms": "twitching of the toes and tail, arching of the head (stargazing), more likely to suffer from parasites or liver failure",
    "description": "Contagious disease among bearded dragons, spread by direct contact or through contaminated hands or other objects.",
    "species_affected": "bearded dragons"
    }
    ]

    for illness in data:
        Illness.objects.create(
        illness_name=illness["illness_name"],
        symptoms=illness["symptoms"],
        description=illness["description"],
        species_affected=illness["species_affected"]
        )



class Migration(migrations.Migration):

    dependencies = [
        ('reptile_app', '0015_auto_20180726_1734'),
    ]

    operations = [
        migrations.RunPython(add_illnesses)
    ]
