# Generated by Django 2.0.7 on 2018-08-01 14:13

from django.db import migrations

def add_vets(apps, schema_editor):
    Vet = apps.get_model("reptile_app", "Vet")
    data = [
    {
    "vet_name": "HealthPointe Veterinary Clinic",
    "raw_address": "740 Shoals Road",
    "raw_address2": "",
    "city": "Duncan",
    "state": "SC",
    "zip_code": "29334",
    "phone": "(864) 486-8177",
    "website": "http://www.healthpointevet.com/",
    "emergency_services": False,
    "boarding_services": True,
    "image": "",
    "notes": ""
    },
    {
    "vet_name": "Cleveland Park East Animal Hospital",
    "raw_address": "815 NE Main Street",
    "raw_address2": "",
    "city": "Simpsonville",
    "state": "SC",
    "zip_code": "29681",
    "phone": "(864) 963–8025",
    "website": "https://www.clevelandparkeast.com/veterinary-services/exotics.html",
    "emergency_services": False,
    "boarding_services": False,
    "image": "",
    "notes": ""
    },
    {
    "vet_name": "Carolina Veterinary Specialists in Charlotte, NC",
    "raw_address": "2225 Township Road",
    "raw_address2": "",
    "city": "Charlotte",
    "state": "NC",
    "zip_code": "28273",
    "phone": "704-504-9608",
    "website": "https://www.carolinavet.com/locations/charlotte-nc/",
    "emergency_services": True,
    "boarding_services": False,
    "image": "",
    "notes": ""
    },
    {
    "vet_name": "Carolina Veterinary Specialists in Greensboro, NC",
    "raw_address": "501 Nicholas Road",
    "raw_address2": "",
    "city": "Greensboro",
    "state": "NC",
    "zip_code": "27409",
    "phone": "336-632-0605",
    "website": "https://www.carolinavet.com/locations/greensboro-nc/",
    "emergency_services": True,
    "boarding_services": False,
    "image": "",
    "notes": ""
    },
    {
    "vet_name": "Carolina Veterinary Specialists in Huntersville, NC",
    "raw_address": "12117 Statesville Rd",
    "raw_address2": "",
    "city": "Huntersville",
    "state": "NC",
    "zip_code": "28078",
    "phone": "704-949-1100",
    "website": "https://www.carolinavet.com/locations/huntersville-nc/",
    "emergency_services": True,
    "boarding_services": False,
    "image": "",
    "notes": ""
    },
    {
    "vet_name": "Carolina Veterinary Specialists in Matthews, NC",
    "raw_address": "4099 Campus Ridge Road",
    "raw_address2": "",
    "city": "Matthews",
    "state": "NC",
    "zip_code": "28104",
    "phone": "704-815-3939",
    "website": "https://www.carolinavet.com/locations/matthews-nc/",
    "emergency_services": True,
    "boarding_services": False,
    "image": "",
    "notes": ""
    },
    {
    "vet_name": "Carolina Veterinary Specialists in Winston-Salem, NC",
    "raw_address": "1600 Hanes Mall Boulevard",
    "raw_address2": "",
    "city": "Winston Salem",
    "state": "NC",
    "zip_code": "27103",
    "phone": "336-896-0902",
    "website": "https://www.carolinavet.com/locations/winston-salem-nc/",
    "emergency_services": True,
    "boarding_services": False,
    "image": "",
    "notes": ""
    },
    {
    "vet_name": "Carolina Veterinary Specialists in Rock Hill, SC",
    "raw_address": "760 Addison Avenue",
    "raw_address2": "",
    "city": "Rock Hill",
    "state": "SC",
    "zip_code": "29730",
    "phone": "803-909-8300",
    "website": "https://www.carolinavet.com/locations/rock-hill-sc/",
    "emergency_services": True,
    "boarding_services": False,
    "image": "",
    "notes": ""
    }
    ]

    for vet in data:
        Vet.objects.create(
        vet_name=vet["vet_name"],
        raw_address=vet["raw_address"],
        raw_address2=vet["raw_address2"],
        city=vet["city"],
        state=vet["state"],
        zip_code=vet["zip_code"],
        phone=vet["phone"],
        website=vet["website"],
        emergency_services=vet["emergency_services"],
        boarding_services=vet["boarding_services"],
        notes=vet["notes"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reptile_app', '0016_auto_20180801_1327'),
    ]

    operations = [
    migrations.RunPython(add_vets)
    ]
